version: "3.7"

services:
  app:
    image: daniil3680/namemaster:latest
    deploy:
      replicas: 1                            # Количество реплик
      placement:
        constraints:
          - node.role == manager              # Размещать только на worker-нодах
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.whoami-http.rule=Host(`whoami.namemaster.online`)
        - traefik.http.routers.whoami-http.entrypoints=http
        - traefik.http.routers.whoami-http.middlewares=https-redirect
        - traefik.http.routers.whoami-https.rule=Host(`whoami.namemaster.online`)
        - traefik.http.routers.whoami-https.entrypoints=https
        - traefik.http.routers.whoami-https.tls=true
        - traefik.http.routers.whoami-https.tls.certresolver=le
        - traefik.http.services.whoami.loadbalancer.server.port=5000
    depends_on:
      - db
    environment:
        postgresql-username: postgres
        postgresql-password: password
        postgresql-host: db
        postgresql-port: 5432
        postgresql-database: mydatabase
        namemaster-secretkey: 9b908738adb74b789012511dce6e0bfe
    networks:
      - traefik-public
      - app

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

networks:
  traefik-public:
    external: true
  app:

volumes:
  postgres_data:
