version: "3.7"

services:
  whoami:
    image: "traefik/whoami"
    deploy:
      replicas: 3                            # Количество реплик
      placement:
        constraints:
          - node.role == worker              # Размещать только на worker-нодах
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.whoami-http.rule=Host(`whoami.namemaster.online`)
        - traefik.http.routers.whoami-http.entrypoints=http
        - traefik.http.routers.whoami-http.middlewares=https-redirect
        - traefik.http.routers.whoami-https.rule=Host(`whoami.namemaster.online`)
        - traefik.http.routers.whoami-https.entrypoints=https
        - traefik.http.routers.whoami-https.tls=true
        - traefik.http.routers.whoami-https.tls.certresolver=le
        - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
