name: CI/CD for Docker Swarm with Compose on Remote Server

on:
  push:
    branches:
      - main  # Триггер только для ветки main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Генерация уникального тега для образа
      - name: Generate unique image tag
        id: tag
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an' | tr -s ' ' '-')  # Заменяем пробелы на дефисы
          COMMIT_HASH=${GITHUB_SHA::7}
          COMMIT_DATE=$(date +'%Y-%m-%d')
          COMMIT_TIME=$(date +'%H%M%S')  # Время в формате HHMMSS
          IMAGE_TAG="${AUTHOR_NAME}-${COMMIT_HASH}-${COMMIT_DATE}-${COMMIT_TIME}"
          IMAGE_TAG=$(echo "$IMAGE_TAG" | tr -cd '[:alnum:]-')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG"
    
    

      # Сборка и пуш Docker-образа
      - name: Build and push Docker image
        run: |
          docker build -f ./app/Dockerfile -t daniil3680/namemaster:$IMAGE_TAG .
          docker push daniil3680/namemaster:$IMAGE_TAG

      # Копирование файлов на удалённый сервер
      - name: Copy files to remote server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./app/compose.yaml"
          target: "~/deployments/namemaster/"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        

      # Обновление тега образа в docker-compose.yml на сервере
      - name: Update docker-compose on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          sed -i 's|daniil3680/namemaster:.*|daniil3680/namemaster:$IMAGE_TAG|g' ~/deployments/namemaster/compose.yaml"

      # Деплой с использованием Docker Compose
      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          docker stack deploy --compose-file ~/deployments/namemaster/compose.yaml namemaster-stack
          "
